### ISSUE TITLE
Version Check Fails on Integer Versions

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-service-yara#12]
Recommend verifying the type of variable provided from the YARA metadata, I am getting a TypeError on the default imported rules. 
`TypeError: argument of type 'int' is not iterable`

The metadata for the checked values can be an integer, boolean, or a string. The current code only handles string revision numbers. 
```
                for k, v in meta.items():
                    if k in ['version', 'rule_version', 'revision']:
                        if isinstance(v, (int, bool, )):
                            # Handle integer or boolean revisions
                            version = str(v)
                        elif "." in v:
                            # Maintain version schema (M.m)
                            version_split = v.split(".", 1)
                            major = ''.join(filter(str.isdigit, version_split[0]))
                            minor = ''.join(filter(str.isdigit, version_split[1]))
                            version = f"{major}.{minor}"
                        else:
                            # Fair to assume number found is the major only
                            version = ''.join(filter(str.isdigit, v))
```

https://github.com/CybercentreCanada/assemblyline-service-yara/blob/d3711d3974e4e381b1757e4f15ef38a798de6e05/yara_/yara_importer.py#L47

**Comment by cccs-rs** [comment]
Hi @malvidin, thanks for catching this in our default setup. This has be fixed thanks to you.
[`Handle integer or boolean revisions`](https://github.com/CybercentreCanada/assemblyline-service-yara/commit/df3e5508c2bdf2690adb9def66e7dd67e953a006)

**Comment by malvidin** [comment]
Thanks for fixing this. Is there any timeline for this to be moved to stable?
The rule name `sitrof_fortis_scar` uses metadata of `version = 2`, which breaks the default Malware YARA import.
https://github.com/Yara-Rules/rules/blob/6636eafa1298ad431b501f1c76df2977229dcbf7/malware_index.yar#L266

**Comment by cccs-rs** [comment]
I'm pushing a new stable now, forgot to create one after the dev tag.
