### ISSUE TITLE
internal error 30

### ISSUE THREAD

**Issue by godfriedmeesters** [CybercentreCanada/assemblyline-service-yara#2]
When processing a file with following characteristics:
Typeunknown
Mimetypetext/plain
MagicISO-8859 text, with very long lines, with no line terminators
Entropy1.0034422692025058

I get:

YARA [EXCEPTION] :: 4.0.0.beta4
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/assemblyline_v4_service/common/base.py", line 79, in handle_task
    self.execute(request)
  File "/opt/al_service/yara_/yara_.py", line 519, in execute
    matches = self.rules.match(local_filename, externals=yara_externals)
Error: internal error: 30

**Comment by cccs-rs** [comment]
There seemed to be a problem with the condition that was meant to catch this error gracefully, this has now been resolved.
[bug fix in error catch](https://github.com/CybercentreCanada/assemblyline-service-yara/commit/a87205c26d72d1a32de6d088deefd4cce9ca4ee9)
