### ISSUE TITLE
Download of yara rules failed 

### ISSUE THREAD

**Issue by marpoe** [CybercentreCanada/assemblyline-service-yara#25]
When i try to run the service for getting intial yara rules, its failed because of TypeErrors.

{"@timestamp": "2022-02-23 07:25:17,101", "event": { "module": "assemblyline", "dataset": "assemblyline.updater.yara" }, "host": { "ip": "xxxxx", "hostname": "1a1971a01502" }, "log": { "level": "ERROR", "logger": "assemblyline.updater.yara" }, "process": { "pid": "1" }, "message": "An error occurred running the update. Will retry...\nTraceback (most recent call last):\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/updater/updater.py\", line 416, in _run_source_updates\n    self.do_source_update(service=service)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/updater/updater.py\", line 345, in do_source_update\n    files = git_clone_repo(source, old_update_time, self.default_pattern, self.log, update_dir) \\\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/updater/helper.py\", line 195, in git_clone_repo\n    repo = Repo.clone_from(url, clone_dir, env=git_env, git_config=git_config)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/git/repo/base.py\", line 1148, in clone_from\n    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/git/repo/base.py\", line 1075, in _clone\n    proc = git.clone(multi, Git.polish_url(str(url)), clone_path, with_extended_output=True, as_process=True,\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/git/cmd.py\", line 638, in <lambda>\n    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/git/cmd.py\", line 1183, in _call_process\n    return self.execute(call, **exec_kwargs)\n  File \"/var/lib/assemblyline/.local/lib/python3.9/site-packages/git/cmd.py\", line 872, in execute\n    proc = Popen(command,\n  File \"/usr/local/lib/python3.9/subprocess.py\", line 951, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/local/lib/python3.9/subprocess.py\", line 1741, in _execute_child\n    env_list.append(k + b'=' + os.fsencode(v))\n  File \"/usr/local/lib/python3.9/os.py\", line 810, in fsencode\n    filename = fspath(filename)  # Does type-checking of `filename`.\nTypeError: expected str, bytes or os.PathLike object, not int\n"}

Do you have any idea how to fix it?

**Comment by cccs-rs** [comment]
Which version of the service?

**Comment by marpoe** [comment]
4.2.0.stable 10 - i had to update to this version. No it works :-) thanks for the fast reply...
