### ISSUE TITLE
Clearer YARA Version Tracking

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-service-yara#4]
If YARA version is provided through an ENV variable, the version used is more clearly visible. Depending on how important caching builds is, the ENV can be defined after `gcc` is installed.
https://github.com/CybercentreCanada/assemblyline-service-yara/blob/29fcfad2da1800f8970b3d0c4cf5037db8435d46/yara_/Dockerfile#L14
```
FROM cccs/assemblyline-v4-service-base:latest AS base
ENV SERVICE_PATH yara_.yara_.Yara
...
ENV YARA_VERSION='3.11.0'
...
RUN wget -O /tmp/yara.tar.gz https://github.com/VirusTotal/yara/archive/v${YARA_VERSION}.tar.gz
...
WORKDIR /tmp/yara-${YARA_VERSION}
...
RUN pip install --no-cache-dir --user yara-python==${YARA_VERSION} gitpython plyara && rm -rf ~/.cache/pip
```

**Comment by cccs-rs** [comment]
PR has been accepted that unifies version changes in Dockerfile.
