### ISSUE TITLE
Yara revision could not convert string to float

### ISSUE THREAD

**Issue by ClovDev** [CybercentreCanada/assemblyline-service-yara#8]
Hi,

When trying to import from the Mcafee ATR (https://github.com/advanced-threat-research/Yara-Rules) yara ruleset I get the following error:
`{"@timestamp": "2020-10-29 09:26:18,764", "event.module": "assemblyline", "event.dataset": "assemblyline.updater.yara", "host.ip": "172.19.0.7", "host.hostname": "0e44f6ba9cd5", "log.level": "ERROR", "log.logger": "assemblyline.updater.yara", "process.pid": "1", "message": "Updater ended with an exception!\nTraceback (most recent call last):\n  File \"/opt/al_service/yara_/yara_updater.py\", line 352, in yara_update\n    raise e\n  File \"/opt/al_service/yara_/yara_updater.py\", line 350, in yara_update\n    yara_importer.import_file(cur_file, source_name, default_classification=default_classification)\n  File \"/opt/al_service/yara_/yara_importer.py\", line 103, in import_file\n    default_status=default_status, default_classification=default_classification)\n  File \"/opt/al_service/yara_/yara_importer.py\", line 93, in import_data\n    default_classification=default_classification)\n  File \"/opt/al_service/yara_/yara_importer.py\", line 69, in _save_signatures\n    revision=int(float(version)),\nValueError: could not convert string to float: 'v1'\n"}`

I see that the version is set at line 40 with a for loop to 'v1' due the rule_version being present. Later at line 69 the string "v1" cannot be converted to float for obvious reasons.

Not sure what would be an appropriate solution in this case. Probably in the background the database and the UI an integer is expected, so switching to string might not be smart.

**Comment by cccs-rs** [comment]
From looking at our other signature sources, it seems they use decimal or float notation for versioning.

We could strip any alphabetic characters and rewrite the "version" so it fits float notation.

ie. v1.2.0.3 -> 1.203

**Comment by ClovDev** [comment]
That makes sense to me, easiest solution would be this then I guess:
version = ''.join(filter(str.isdigit,v)) at line 47

Can try to find out how to do PR tomorrow if wanted, not a true programmer :)

**Comment by cccs-rs** [comment]
Sure, if you have any code that you think we can use to fix this problem (or others), I'd be happy to look over it! 😀

**Comment by ClovDev** [comment]
Looks like a nice fix to me, thanks 😃
